export const CLOTHING_TERMS = [
    // Tops
    "T-shirt", "Blouse", "Shirt", "Tank top", "Crop top", "Tube top", "Halter top", "Camisole", "Tunic", "Bodysuit",
    "Sweater", "Cardigan", "Pullover", "Jumper", "Hoodie", "Sweatshirt", "Fleece", "Turtleneck", "Mock neck", "V-neck",
    "Crew neck", "Scoop neck", "Boat neck", "Off-the-shoulder", "One-shoulder", "Wrap top", "Peplum top", "Corset", "Bustier",
    "Button-down", "Oxford shirt", "Flannel shirt", "Chambray shirt", "Denim shirt", "Linen shirt", "Silk shirt", "Satin blouse",
    "Chiffon blouse", "Lace top", "Mesh top", "Sheer top", "Graphic tee", "Polo shirt", "Henley", "Rugby shirt", "Baseball tee",
    "Ringer tee", "Muscle tee", "Oversized tee", "Fitted tee", "Long sleeve tee", "Short sleeve tee", "Sleeveless top",
    "Cap sleeve top", "Bell sleeve top", "Puff sleeve top", "Bishop sleeve top", "Dolman sleeve top", "Kimono sleeve top",
    "Raglan sleeve top", "Cold shoulder top", "Cutout top", "Asymmetrical top", "Draped top", "Ruched top", "Smocked top",
    "Tie-front top", "Knotted top", "Backless top", "Halter neck top", "Spaghetti strap top", "Strapless top", "Bandeau",

    // Bottoms
    "Jeans", "Skinny jeans", "Straight leg jeans", "Bootcut jeans", "Flare jeans", "Wide leg jeans", "Boyfriend jeans",
    "Mom jeans", "Dad jeans", "High-waisted jeans", "Low-rise jeans", "Mid-rise jeans", "Ripped jeans", "Distressed jeans",
    "Acid wash jeans", "Raw hem jeans", "Cuffed jeans", "Cropped jeans", "Ankle jeans", "Capri pants", "Cargo pants",
    "Chinos", "Khakis", "Slacks", "Trousers", "Dress pants", "Suit pants", "Pleated pants", "Flat front pants", "Joggers",
    "Sweatpants", "Track pants", "Leggings", "Jeggings", "Yoga pants", "Bike shorts", "Running shorts", "Gym shorts",
    "Bermuda shorts", "Denim shorts", "Cutoffs", "High-waisted shorts", "Paperbag waist shorts", "Culottes", "Palazzo pants",
    "Gaucho pants", "Harem pants", "Parachute pants", "Leather pants", "Faux leather pants", "Vinyl pants", "Corduroy pants",
    "Velvet pants", "Linen pants", "Silk pants", "Satin pants", "Wool pants", "Tweed pants", "Plaid pants", "Striped pants",
    "Floral pants", "Animal print pants", "Camouflage pants", "Skirt", "Mini skirt", "Midi skirt", "Maxi skirt", "Pencil skirt",
    "A-line skirt", "Pleated skirt", "Circle skirt", "Skater skirt", "Tennis skirt", "Wrap skirt", "Tulip skirt", "Bubble skirt",
    "Tiered skirt", "Ruffled skirt", "Asymmetrical skirt", "High-low skirt", "Slit skirt", "Button-front skirt", "Denim skirt",
    "Leather skirt", "Suede skirt", "Velvet skirt", "Silk skirt", "Satin skirt", "Chiffon skirt", "Tulle skirt", "Lace skirt",
    "Sequin skirt", "Kilt", "Sarong",

    // Dresses & Jumpsuits
    "Dress", "Mini dress", "Midi dress", "Maxi dress", "Gown", "Evening gown", "Cocktail dress", "Party dress", "Sundress",
    "Summer dress", "Slip dress", "Shift dress", "Sheath dress", "Bodycon dress", "Wrap dress", "Shirt dress", "T-shirt dress",
    "Sweater dress", "Jumper dress", "Pinafore dress", "Overall dress", "Dungaree dress", "Tea dress", "Smock dress",
    "Babydoll dress", "Empire waist dress", "Drop waist dress", "Fit and flare dress", "Skater dress", "A-line dress",
    "Ball gown", "Mermaid dress", "Trumpet dress", "Column dress", "Halter dress", "One-shoulder dress", "Off-the-shoulder dress",
    "Strapless dress", "Backless dress", "Cutout dress", "Asymmetrical dress", "High-low dress", "Tiered dress", "Ruffled dress",
    "Pleated dress", "Draped dress", "Ruched dress", "Smocked dress", "Lace dress", "Sequin dress", "Beaded dress",
    "Embroidered dress", "Floral dress", "Polka dot dress", "Striped dress", "Animal print dress", "Little black dress (LBD)",
    "Little white dress", "Wedding dress", "Bridesmaid dress", "Prom dress", "Jumpsuit", "Romper", "Playsuit", "Overalls",
    "Dungarees", "Boilersuit", "Catsuit", "Unitard",

    // Outerwear
    "Jacket", "Coat", "Blazer", "Vest", "Cardigan", "Pullover", "Hoodie", "Sweatshirt", "Denim jacket", "Jean jacket",
    "Leather jacket", "Moto jacket", "Biker jacket", "Bomber jacket", "Varsity jacket", "Letterman jacket", "Windbreaker",
    "Track jacket", "Puffer jacket", "Down jacket", "Quilted jacket", "Parka", "Anorak", "Raincoat", "Trench coat",
    "Pea coat", "Overcoat", "Topcoat", "Duster coat", "Cape", "Poncho", "Shawl", "Wrap", "Shrug", "Bolero", "Kimono",
    "Teddy coat", "Faux fur coat", "Shearling coat", "Sheepskin coat", "Wool coat", "Cashmere coat", "Camel coat",
    "Chesterfield coat", "Duffle coat", "Cocoon coat", "Swing coat", "Military jacket", "Field jacket", "Safari jacket",
    "Utility jacket", "Shirt jacket", "Shacket", "Fleece jacket", "Softshell jacket", "Ski jacket", "Snowboard jacket",

    // Shoes
    "Shoes", "Sneakers", "Trainers", "Running shoes", "Walking shoes", "Gym shoes", "Tennis shoes", "Basketball shoes",
    "High-tops", "Low-tops", "Slip-ons", "Canvas shoes", "Plimsolls", "Deck shoes", "Boat shoes", "Loafers", "Moccasins",
    "Driving shoes", "Espadrilles", "Sandals", "Flip-flops", "Slides", "Gladiator sandals", "Wedge sandals", "Platform sandals",
    "Heeled sandals", "Strappy sandals", "Mules", "Clogs", "Slippers", "Boots", "Ankle boots", "Booties", "Chelsea boots",
    "Chukka boots", "Desert boots", "Combat boots", "Work boots", "Hiking boots", "Snow boots", "Rain boots", "Wellington boots",
    "Riding boots", "Cowboy boots", "Western boots", "Knee-high boots", "Over-the-knee boots", "Thigh-high boots", "Heels",
    "High heels", "Stilettos", "Pumps", "Court shoes", "Kitten heels", "Block heels", "Wedge heels", "Platform heels",
    "Slingbacks", "Peep-toe shoes", "Mary Janes", "Oxfords", "Derby shoes", "Brogues", "Monk strap shoes", "Ballet flats",
    "Flats", "Pointed toe flats",

    // Accessories
    "Bag", "Handbag", "Purse", "Clutch", "Wallet", "Backpack", "Rucksack", "Tote bag", "Shopper bag", "Shoulder bag",
    "Crossbody bag", "Messenger bag", "Satchel", "Briefcase", "Laptop bag", "Duffel bag", "Weekender bag", "Gym bag",
    "Travel bag", "Suitcase", "Luggage", "Fanny pack", "Belt bag", "Waist bag", "Bucket bag", "Hobo bag", "Saddle bag",
    "Baguette bag", "Wristlet", "Coin purse", "Card holder", "Belt", "Leather belt", "Fabric belt", "Chain belt", "Corset belt",
    "Obi belt", "Sash", "Suspenders", "Braces", "Tie", "Necktie", "Bow tie", "Cravat", "Ascot", "Pocket square", "Scarf",
    "Winter scarf", "Infinity scarf", "Blanket scarf", "Silk scarf", "Satin scarf", "Chiffon scarf", "Bandana", "Neckerchief",
    "Headscarf", "Hat", "Cap", "Baseball cap", "Trucker cap", "Snapback", "Beanie", "Knit hat", "Bobble hat", "Beret",
    "Fedora", "Trilby", "Panama hat", "Sun hat", "Straw hat", "Floppy hat", "Bucket hat", "Boater hat", "Newsboy cap",
    "Flat cap", "Baker boy hat", "Visor", "Headband", "Hair tie", "Scrunchie", "Hair clip", "Barrette", "Bobby pin",
    "Hairpin", "Tiara", "Crown", "Fascinator", "Sunglasses", "Glasses", "Reading glasses", "Eyewear", "Jewelry",
    "Necklace", "Choker", "Pendant", "Chain", "Earrings", "Studs", "Hoops", "Dangle earrings", "Drop earrings",
    "Chandelier earrings", "Cuff earrings", "Bracelet", "Bangle", "Cuff", "Chain bracelet", "Charm bracelet", "Anklet",
    "Ring", "Band", "Signet ring", "Cocktail ring", "Watch", "Wristwatch", "Smartwatch", "Gloves", "Mittens", "Fingerless gloves",
    "Socks", "Ankle socks", "Crew socks", "Knee-high socks", "Over-the-knee socks", "Tights", "Stockings", "Pantyhose",
    "Leg warmers",

    // Fabrics & Materials
    "Cotton", "Wool", "Linen", "Silk", "Satin", "Chiffon", "Velvet", "Corduroy", "Denim", "Leather", "Faux leather",
    "Suede", "Faux suede", "Fur", "Faux fur", "Shearling", "Fleece", "Flannel", "Tweed", "Plaid", "Tartan", "Gingham",
    "Houndstooth", "Stripes", "Polka dots", "Floral", "Paisley", "Animal print", "Leopard print", "Zebra print",
    "Snake print", "Camouflage", "Tie-dye", "Ombre", "Gradient", "Metallic", "Sequin", "Glitter", "Beaded", "Embroidered",
    "Lace", "Mesh", "Sheer", "Tulle", "Organza", "Taffeta", "Brocade", "Jacquard", "Damask", "Chenille", "Cashmere",
    "Mohair", "Angora", "Alpaca", "Merino wool", "Polyester", "Nylon", "Spandex", "Elastane", "Lycra", "Rayon", "Viscose",
    "Modal", "Bamboo", "Hemp", "Jute", "Canvas", "Twill", "Herringbone", "Ribbed", "Knitted", "Crocheted", "Woven",
    "Braided", "Quilted", "Padded", "Insulated", "Waterproof", "Water-resistant", "Windproof", "Breathable", "Stretchy",

    // Styles & Aesthetics
    "Casual", "Formal", "Business casual", "Smart casual", "Professional", "Workwear", "Office wear", "Evening wear",
    "Party wear", "Cocktail attire", "Black tie", "White tie", "Wedding guest", "Bridal", "Athleisure", "Sporty",
    "Activewear", "Gym wear", "Loungewear", "Sleepwear", "Pajamas", "Lingerie", "Underwear", "Swimwear", "Beachwear",
    "Resort wear", "Vacation wear", "Festival wear", "Concert wear", "Club wear", "Streetwear", "Urban", "Hipster",
    "Bohemian", "Boho", "Chic", "Elegant", "Sophisticated", "Classy", "Timeless", "Classic", "Minimalist", "Maximalist",
    "Retro", "Vintage", "Antique", "Thrifted", "Secondhand", "Upcycled", "Sustainable", "Eco-friendly", "Ethical",
    "Slow fashion", "Fast fashion", "High fashion", "Couture", "Designer", "Luxury", "Preppy", "Ivy League", "Collegiate",
    "Grunge", "Punk", "Goth", "Emo", "Rocker", "Edgy", "Alternative", "Indie", "Artsy", "Eclectic", "Quirky", "Funky",
    "Colorful", "Bright", "Bold", "Vibrant", "Pastel", "Neutral", "Monochrome", "Earth tones", "Jewel tones", "Neon",
    "Fluorescent", "Dark", "Light", "Soft", "Hard", "Masculine", "Feminine", "Androgynous", "Unisex", "Gender-neutral",
    "Modest", "Conservative", "Sexy", "Revealing", "Tight", "Loose", "Baggy", "Oversized", "Fitted", "Tailored",
    "Structured", "Flowy", "Relaxed", "Comfortable", "Cozy", "Warm", "Cool", "Summer", "Winter", "Spring", "Autumn",
    "Fall", "Seasonal", "Trendy", "Fashionable", "Stylish"
];
