import { v } from "convex/values";
export const outfitStatus = v.union(
  v.literal("suggested"),
  v.literal("planned"),
  v.literal("worn"),
  v.literal("dismissed"),
);
export const outfitFields = {
  userId: v.string(),
  date: v.string(),
  title: v.string(),
  rationale: v.string(),
  context: v.array(v.string()),
  itemIds: v.array(v.id("wardrobeItems")),
  missing: v.array(v.string()),
  status: outfitStatus,
  calendarDerived: v.boolean(),
  createdAt: v.number(),
  updatedAt: v.number(),
  reason: v.optional(v.string()),
  planRevision: v.optional(v.number()),
  wearOccurrenceId: v.optional(v.id("wearOccurrences")),
  reminderScheduleRevision: v.optional(v.number()),
  reminderCalendarId: v.optional(v.string()),
  reminderEventId: v.optional(v.string()),
  reminderCalendarRevision: v.optional(v.number()),
  reminderCalendarCheckedAt: v.optional(v.number()),
  reminderCalendarActive: v.optional(v.boolean()),
  reminderNextRefreshAt: v.optional(v.number()),
  reminderStartsAt: v.optional(v.number()),
  reminderEndsAt: v.optional(v.number()),
  reminderTimezone: v.optional(v.string()),
  reminderTimeConfirmedAt: v.optional(v.number()),
  notWornAt: v.optional(v.number()),
};
