import type { Document } from "@confect/server";
import type schemaDefinition from "./schema";

export type CandidateItemsDoc = Document.Document<typeof schemaDefinition, "candidateItems">;
export type DeletedAccountsDoc = Document.Document<typeof schemaDefinition, "deletedAccounts">;
export type FitCheckItemsDoc = Document.Document<typeof schemaDefinition, "fitCheckItems">;
export type FitChecksDoc = Document.Document<typeof schemaDefinition, "fitChecks">;
export type GarmentObservationsDoc = Document.Document<typeof schemaDefinition, "garmentObservations">;
export type NotificationAttemptsDoc = Document.Document<typeof schemaDefinition, "notificationAttempts">;
export type NotificationBudgetsDoc = Document.Document<typeof schemaDefinition, "notificationBudgets">;
export type NotificationInstallationsDoc = Document.Document<typeof schemaDefinition, "notificationInstallations">;
export type NotificationIntentsDoc = Document.Document<typeof schemaDefinition, "notificationIntents">;
export type NotificationPreferencesDoc = Document.Document<typeof schemaDefinition, "notificationPreferences">;
export type OutfitSuggestionsDoc = Document.Document<typeof schemaDefinition, "outfitSuggestions">;
export type PlanRevisionsDoc = Document.Document<typeof schemaDefinition, "planRevisions">;
export type PlanningSettingsDoc = Document.Document<typeof schemaDefinition, "planningSettings">;
export type ProfileBioRevisionsDoc = Document.Document<typeof schemaDefinition, "profileBioRevisions">;
export type ProfilesDoc = Document.Document<typeof schemaDefinition, "profiles">;
export type StorageObjectsDoc = Document.Document<typeof schemaDefinition, "storageObjects">;
export type StyleBioJobsDoc = Document.Document<typeof schemaDefinition, "styleBioJobs">;
export type SubscriptionsDoc = Document.Document<typeof schemaDefinition, "subscriptions">;
export type UploadTicketsDoc = Document.Document<typeof schemaDefinition, "uploadTickets">;
export type UploadsDoc = Document.Document<typeof schemaDefinition, "uploads">;
export type WardrobeItemsDoc = Document.Document<typeof schemaDefinition, "wardrobeItems">;
export type WardrobeMembershipsDoc = Document.Document<typeof schemaDefinition, "wardrobeMemberships">;
export type WardrobesDoc = Document.Document<typeof schemaDefinition, "wardrobes">;
export type WearEvidenceDoc = Document.Document<typeof schemaDefinition, "wearEvidence">;
export type WearGraphLocksDoc = Document.Document<typeof schemaDefinition, "wearGraphLocks">;
export type WearGraphNodesDoc = Document.Document<typeof schemaDefinition, "wearGraphNodes">;
export type WearOccurrencesDoc = Document.Document<typeof schemaDefinition, "wearOccurrences">;
export type WearProjectionOutboxDoc = Document.Document<typeof schemaDefinition, "wearProjectionOutbox">;
export type WearRevisionsDoc = Document.Document<typeof schemaDefinition, "wearRevisions">;

export interface Docs {
  candidateItems: CandidateItemsDoc;
  deletedAccounts: DeletedAccountsDoc;
  fitCheckItems: FitCheckItemsDoc;
  fitChecks: FitChecksDoc;
  garmentObservations: GarmentObservationsDoc;
  notificationAttempts: NotificationAttemptsDoc;
  notificationBudgets: NotificationBudgetsDoc;
  notificationInstallations: NotificationInstallationsDoc;
  notificationIntents: NotificationIntentsDoc;
  notificationPreferences: NotificationPreferencesDoc;
  outfitSuggestions: OutfitSuggestionsDoc;
  planRevisions: PlanRevisionsDoc;
  planningSettings: PlanningSettingsDoc;
  profileBioRevisions: ProfileBioRevisionsDoc;
  profiles: ProfilesDoc;
  storageObjects: StorageObjectsDoc;
  styleBioJobs: StyleBioJobsDoc;
  subscriptions: SubscriptionsDoc;
  uploadTickets: UploadTicketsDoc;
  uploads: UploadsDoc;
  wardrobeItems: WardrobeItemsDoc;
  wardrobeMemberships: WardrobeMembershipsDoc;
  wardrobes: WardrobesDoc;
  wearEvidence: WearEvidenceDoc;
  wearGraphLocks: WearGraphLocksDoc;
  wearGraphNodes: WearGraphNodesDoc;
  wearOccurrences: WearOccurrencesDoc;
  wearProjectionOutbox: WearProjectionOutboxDoc;
  wearRevisions: WearRevisionsDoc;
}
