import registeredFunctions from "../confect/_generated/registeredFunctions/wardrobe";

export const applyDescription = registeredFunctions.applyDescription;
export const applyEmbedding = registeredFunctions.applyEmbedding;
export const applyFullAnalysis = registeredFunctions.applyFullAnalysis;
export const applyTags = registeredFunctions.applyTags;
export const applyVisualEmbedding = registeredFunctions.applyVisualEmbedding;
export const createWardrobeItem = registeredFunctions.createWardrobeItem;
export const deleteWardrobeItem = registeredFunctions.deleteWardrobeItem;
export const getUploadUrl = registeredFunctions.getUploadUrl;
export const getWardrobeItem = registeredFunctions.getWardrobeItem;
export const getWardrobeItemInternal = registeredFunctions.getWardrobeItemInternal;
export const getWardrobeItemWithUrl = registeredFunctions.getWardrobeItemWithUrl;
export const getWardrobeItemsDisplayByIds = registeredFunctions.getWardrobeItemsDisplayByIds;
export const itemDetails = registeredFunctions.itemDetails;
export const listItemsForSimilarity = registeredFunctions.listItemsForSimilarity;
export const listItemsMissingVisualEmbedding = registeredFunctions.listItemsMissingVisualEmbedding;
export const listWardrobeItems = registeredFunctions.listWardrobeItems;
export const pageCollections = registeredFunctions.pageCollections;
export const pageInspiration = registeredFunctions.pageInspiration;
export const pagePieces = registeredFunctions.pagePieces;
export const pageWardrobeItems = registeredFunctions.pageWardrobeItems;
export const saveNote = registeredFunctions.saveNote;
export const searchGarmentIdentityCandidates = registeredFunctions.searchGarmentIdentityCandidates;
export const searchSimilarItems = registeredFunctions.searchSimilarItems;
export const setAnalysisError = registeredFunctions.setAnalysisError;
export const setAnalysisStatus = registeredFunctions.setAnalysisStatus;
